### PR TITLE
Npm

### PR DESCRIPTION
**Pull request by kiarn**
Run npm install, and move the dir `node_modules` as `resources/vendor`, because I didn't find an usefull option to directly install the libs in `resources/vendor` (didn't work with `-g --prefix=PATH` ).

Is it necessary to delete `package-lock.json` ?

Next step : convert the bower deps as npm deps ( not the same names, neither versions ... ).

### CODE REVIEW

**Comment by Eugeny** [comment]
I think it's a better idea to just keep it at `node_modules` - this is more predictable for the user. The `package-lock.json` file should be committed together with `package.json`

**Comment by kiarn** [comment]
Ok, then it's necessary to modify `build` as well.
If you are ok with this, I will let `build` scan for both `node_modules` and `resources/vendor` simultaneously to compile the resources. This way let me the possibility to use both package manager the time I resolve all dependencies in the plugins.
And then I will remove the scan in `resources/vendor`.

**Comment by kiarn** [comment]
Done.

**Comment by Eugeny** [comment]
Great!

**Pull request merged**
